POST http://localhost:8080/characters HTTP/1.1
Content-Type: application/json

{
  "name": "広川卯月",
  "characterInfo": {
    "birthDate": "1999-04-30",
    "gender": "女"
  }
}

###

PUT http://localhost:8080/characters/4 HTTP/1.1
Content-Type: application/json

{
  "name": "豊浜のどか",
  "characterInfo": {
    "birthDate": "1999-03-14",
    "gender": "女"
  }
}

###

GET http://localhost:8080/characters HTTP/1.1

###

GET http://localhost:8080/characters/1 HTTP/1.1

###

# DELETE http://localhost:8080/characters/4 HTTP/1.1

###

# GET http://localhost:8080/characters/find?name=梓川 HTTP/1.1
